Feature/services
KaguasBest/DreamYachts pull request #12
Opened 2023-07-29 16:20 UTC by Mitka92

Завершив роботу над секцією

2023-07-29 18:55 UTC, KaguasBest requested changes
.rest-button {
        line-height: 110%;  - заміни на 1.1

Перевір в html правильність величин
max-width:1279.98px
Зроби цілими числами

Все чудово. Дякую!!!

2023-07-30 06:41 UTC, KaguasBest commented
Додатково!!! 
rest-section перенеси із section і створи <div class=container rest-container (твій rest-section)> 
Тобто весь код, який знаходиться між тегами <section>...</section> потрібно огорнути в додатковий div. 
Потім відповідно змінити rest.css так щоб відповідало реаліям.
Дякую. Чекаю на виправлення.

2023-07-30 08:06 UTC, Mitka92 commented
Зробив виправлення, видалив картинки тому, що їх не використовував.

2023-07-30 14:09 UTC, KaguasBest approved these changes
Good

2023-07-30 15:46 UTC, KaguasBest approved these changes

2023-07-31 09:31 UTC, KaguasBest approved these changes

2023-07-31 09:37 UTC, KaguasBest approved these changes

2023-07-31 09:41 UTC, KaguasBest approved these changes

2023-07-31 09:51 UTC, KaguasBest approved these changes

2023-07-31 09:56 UTC, KaguasBest approved these changes

2023-07-31 10:00 UTC, KaguasBest approved these changes

2023-07-31 10:03 UTC, merged