saturday
KaguasBest/DreamYachts pull request #14
Opened 2023-07-29 17:14 UTC by AnnaRychkova1

2023-07-29 17:41 UTC, AustinsGroove requested changes
побажання :)

2023-07-29 17:41 UTC, AustinsGroove commented on src/css/hero.css
> +  line-height: 1, 1;
зайвий пробіл, крапка замість коми

2023-07-29 17:41 UTC, AustinsGroove commented on src/css/reset.css
> +    letter-spacing: -2.7px;
---

2023-07-30 12:18 UTC, KaguasBest approved these changes
Приймаю!!!

2023-07-30 12:18 UTC, merged