header-just-begin
KaguasBest/DreamYachts pull request #7
Opened 2023-07-28 19:16 UTC by Dima-S13

2023-07-28 19:55 UTC, KaguasBest requested changes
1. Перевір чи підключений і активний у тебе Prettier, якщо він не встановлений. Бо багато пробілів, важко сприймати в css файлі що і до чого відноситься. Тим паче, коли фігурна душка прилипла до атрибуту.

2. Видали зайві параметри в css файлі, які збігаються з загальними, що прописані в style.css. Бо багато дублюючого коду. 
- font-family: DM Sans;
- font-style: normal;

3. Перероби header.html. Приведи назви класів загальної домовленості. Назва, буль-якого, класу починається з назви секції. Бо потім буде ментор бачити розбіжності і задавати питання або все одно відправить на доопрацювання.

Дякую. Гарно попрацював!!!!

2023-07-28 19:55 UTC, KaguasBest commented on src/partials/header.html
> +            <img class="logo-img" src="../img/header/yaht-icon.svg" alt="logo">Yacht Adventures
Перед кожною назвою класів ОБОВ'ЯЗКОВО додавай header
header-logo-img
і так далі. Щоб ніде більше не було конфліктів

2023-07-28 19:55 UTC, KaguasBest commented on src/partials/header.html
> +            <ul class="navigation-list">
header-...

2023-07-28 19:55 UTC, KaguasBest commented on src/css/header.css
> +font-family: DM Sans;
зайве

2023-07-28 19:55 UTC, KaguasBest commented on src/css/header.css
> +line-height: 114%; /* 15.96px */
line-height: 114%; /* 15.96px */
замін на 
line-height: 1.4;

2023-07-28 19:55 UTC, KaguasBest commented on src/css/header.css
> +text-transform: uppercase;}
зайве

2023-07-29 18:50 UTC, KaguasBest requested changes
Також не знайшов у тебе в css прописаного стилю для лінії під хедером. Вона додаються за допомогою after. Симантично правильно такі елементи відносяться до header i footer. Додай його, будь ласка, щоб потім меньше роботи було. Дякую!!!

2023-07-30 13:54 UTC, KaguasBest approved these changes
Nice))))

2023-07-30 14:02 UTC, KaguasBest approved these changes
Goood!!!

2023-07-30 14:05 UTC, KaguasBest approved these changes
Gooood!!!

2023-07-30 14:07 UTC, merged

2023-08-01 10:12 UTC, Dima-S13 commented
Привiт.
Виправив розмiри "бургера" який ламав контейнер на моб. версii.